---
title: "YTB_search"
author: "ismayil"
date: "2/11/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tuber)
app_id = '570143920296-d6n69c7bm713edtm3vffmtq46t0751pm.apps.googleusercontent.com'

app_secret = 'DB27e-L6XpKcAOx6UyK1hv0i'




# establishing connecting with YouTube




# credentials 

yt_oauth(app_id = app_id, app_secret = app_secret)



```


```{r}



videos_year <- yt_search("Comedy UK")

videostats = lapply(as.character(videos_year$video_id), function(x){
  get_stats(video_id = x)
})
library(plyr)

df = ldply(videostats, data.frame)

# merging videos stats with the main file:  videos_year
colnames(df)[1] = 'video_id' # renaming 'id' as video_id so that it matches same coluimn in main table

library(dplyr)
videos_year = videos_year %>% left_join(df, by = 'video_id')

# correcting data type
videos_year[,c('viewCount', 'likeCount', 'dislikeCount', 'favoriteCount', 'commentCount')]=apply(videos_year[,c('viewCount', 'likeCount', 'dislikeCount', 'favoriteCount', 'commentCount')],2,as.numeric)




# converting into data type 'date'
videos_year$publishedAt = as.Date(videos_year$publishedAt)
str(videos_year$publishedAt)





#install.packages("lubridate")
library(lubridate)
# creating new variables 'year' and 'month'
videos_year = videos_year %>% mutate(month = month(publishedAt)) %>% mutate(year = year(publishedAt))



library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
#install.packages("factoextra")
library(factoextra) # clustering algorithms & visualization



# cleaning video titles
videos_year$title= gsub("<.*?>","", videos_year$title) #removing html tags
videos_year$title= gsub("[[:punct:]]", " ", videos_year$title) #removing html tags
videos_year$title = gsub("[ |\t]{2,}", " ", videos_year$title)  # Remove tabs
videos_year$title = gsub("^ ", "", videos_year$title)  # Leading blanks
videos_year$title = gsub(" $", "", videos_year$title)  # Lagging blanks
videos_year$title = gsub(" +", " ", videos_year$title) # General spaces 
videos_year$title = tolower(videos_year$title) # lowering all letters
# correcting data type
videos_year[,c('viewCount', 'likeCount', 'dislikeCount', 'favoriteCount', 'commentCount')]=apply(videos_year[,c('viewCount', 'likeCount', 'dislikeCount', 'favoriteCount', 'commentCount')],2,as.numeric)




write.csv(videos_year,'ComedyUK.csv', row.names = FALSE)
```
```{r}
library(ggplot2)
#videos<-read.csv("movies_duration.csv")
dat<- read.csv('Comedy.csv')
#dat<- rbind(videos,dat)
#write.csv(dat,"Film&Animation.csv")
dat <- na.omit(dat)
View(dat)
cor(dat$viewCount,dat$likeCount,method = "pearson")
     



## Basic histogram from the vector "rating". Each bin is .5 wide.
## These both result in the same output:
 #ggplot(dat, aes(x=duration)) + geom_histogram(binwidth=.5)
# # # qplot(dat$rating, binwidth=.5)
# # 
# # # Draw with black outline, white fill
#  ggplot(dat, aes(x=duration)) +
#     geom_histogram(binwidth=.5, colour="black", fill="white")

# Density curve
ggplot(dat, aes(x=duration)) + geom_density()


```

