---
title: "movies"
author: "ismayil"
date: "2/10/2020"
output: html_document
---

```{r}
travel2017 = read.csv('travel2017.csv')
travel2018 = read.csv('travel2018.csv')

travel2020 = read.csv('travel2020.csv')
travel2016 = read.csv('travel2016.csv')
travel2014 = read.csv('travel2014.csv')
travel2015 = read.csv('travel2015.csv')

travel=rbind(travel2017,travel2018,travel2016, travel2017,travel2020,travel2015,travel2014)
#mov=rbind(movies2020,movies2014,movies2016)
write.csv(travel,'travel.csv', row.names = FALSE)
```


```{r}
videos_year=travel
  library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
#install.packages("factoextra")
library(factoextra) # clustering algorithms & visualization
videos_year = videos_year %>%
  mutate(like_ratio = likeCount/viewCount) %>% 
  mutate(dislike_ratio = dislikeCount/viewCount) %>%
  mutate(comment_ratio = commentCount/viewCount) %>% 
  mutate(ratio_to_total = viewCount/sum(viewCount, na.rm = TRUE))
write.csv(videos_year,'cleaned_youtube_video_2018-2019.csv', row.names = FALSE)
df <- na.omit(videos_year)
videos_year<- na.omit(videos_year)
df$publishedAt <- NULL
df$channelId <- NULL
df$ratio_to_total<- NULL
df$thumbnails.default.url<- NULL
df$thumbnails.default.width<- NULL
df$thumbnails.high.height<- NULL
df$dislike_ratio<- NULL
df$like_ratio<- NULL
df$description<- NULL
df$thumbnails.high.url<- NULL

df$channelTitle<- NULL
df$liveBroadcastContent<- NULL
df$thumbnails.medium.width<- NULL
df$thumbnails.medium.url<- NULL
df$title<- NULL
df$video_id<- NULL
df$comment_ratio<- NULL
df$thumbnails.default.height<- NULL
df$thumbnails.medium.height<- NULL
df$thumbnails.high.width<- NULL
df$favoriteCount<- NULL
df$dislikeCount<- NULL
dx=df



df$month <- NULL
df$year <- NULL
df <- scale(df)
library(factoextra)
distance <- get_dist(df)
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

k2 <- kmeans(df, centers = 2, nstart = 25)
str(k2)

k2

```

```{r}
fviz_cluster(k2, data = df)
```


```{r}
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)

# plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)
```
```{r}
set.seed(123)
library(cluster)
gap_stat <- clusGap(df, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)
# Print the result
print(gap_stat, method = "firstmax")
```
```{r}
# function to compute average silhouette for k clusters
avg_sil <- function(k) {
  km.res <- kmeans(df, centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(df))
  mean(ss[, 3])
}

# Compute and plot wss for k = 2 to k = 15
k.values <- 2:15
library(purrr)
# extract avg silhouette for 2-15 clusters
avg_sil_values <- map_dbl(k.values, avg_sil)

plot(k.values, avg_sil_values,
       type = "b", pch = 19, frame = FALSE, 
       xlab = "Number of clusters K",
       ylab = "Average Silhouettes")
```
```{r}
fviz_nbclust(df, kmeans, method = "silhouette")
```


```{r}
fviz_gap_stat(gap_stat)
```
```{r}
set.seed(123)
final <- kmeans(df, 3, nstart = 25)
final

```
```{r}
fviz_cluster(final, data = df)
```
```{r}
#install.packages("flexclust")

library("flexclust")
```

```{r}

table(k2$cluster, k3$cluster)

randIndex(k2$cluster, k3$cluster, correct = FALSE)



```

